1 semestre/TourGuide/TourGuide/urls.py
from django.contrib import admin
from django.conf.urls import  include
from django.urls import path
from apps.Usuario.views import index


urlpatterns = [
    #path('admin/', admin.site.urls),

    path('',index, name = 'index'),

    path('login/', include('apps.Usuario.urls' , namespace = 'login')),

]

1 semestre/TourGuide/apps/Usuario/urls.py
from django.conf.urls import url, include

from apps.Usuario.views import index,user_login,User_index_view,info,logout_view,Historial,view_information,view_Profile,register
from django.urls import path


app_name = 'apps'
urlpatterns=[

	path('Home/',index, name = "index"),
	path('Login/',user_login,name = "login"),
	path('User/',User_index_view,name='User_index_view'),
	path('Result/',info, name = 'rresult'),
	path('',logout_view, name = 'logout'),
	path('Record/',Historial, name = 'Historial'),
	path('<int:imagen_id>/',view_information, name = 'informacion'),
	path('Profile/<slug:id>/',view_Profile,name='profile'),
	path('reg_form/',register,name='register')


]

1 semestre/TourGuide/apps/Usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date

# Create your models here.


class ImagenInfo(models.Model):
    idimagen = models.AutoField( primary_key=True) 
    nombreimagen = models.CharField( max_length=45)  
    ciudad = models.CharField( max_length=15)  
    provincia = models.CharField( max_length=15)  
    distrito = models.CharField( max_length=15)  
    direccion = models.CharField( max_length=15)  
    longitud = models.CharField(max_length=45)
    latitud = models.CharField(max_length=45)
    description = models.TextField(max_length=2000)
    construccion = models.CharField( max_length=20, blank=True, null=True)  
    estilo_arquitectonico = models.CharField( max_length=20, blank=True, null=True)  

class HistorialUsuario(models.Model):
    #idhistorial_usuario = models.AutoField(db_column='idHistorial_Usuario', primary_key=True)  # Field name made lowercase.
    user = models.ForeignKey(User, null = True , blank = True , on_delete = models.CASCADE) 
    ImagenInfo = models.ForeignKey(ImagenInfo, null = True , blank = True , on_delete = models.CASCADE)  
    Register_date = models.DateTimeField(auto_now_add=True)

1 semestre/TourGuide/apps/Usuario/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

class UserForm(forms.ModelForm):

	class Meta:
		model = User
		fields =  [
			'email',
			'password',			
		]

		labels = {
			'Email' : 'email',
			'Password': 'password',
		}
		widgets = {

			'email':forms.TextInput(attrs={'class':'form-control',
				'type' :'email', 
				'id':"email", 
				'required': True,	
				'placeholder':"email@example.com"}),
			'password':forms.PasswordInput(attrs={'class':'form-control',
				'id':"password",
				'placeholder' : "Password"

				}),


		}	

'''class RegistroForm(UserCreationForm):

	class Meta:
		model = User
		fields = [
				'username',
				'first_name',
				'last_name',
				'email',
				'password',
			]
		labels = {
				'username': 'Nombre de usuario',
				'first_name': 'Nombre',
				'last_name': 'Apellidos',
				'email': 'Correo',
				'password' : 'Password'
		}

'''










class CustomUserCreationForm(forms.Form):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150,widget = forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label='Enter email',widget = forms.TextInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(label = 'Nombres',widget = forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(label = 'Apellidos',widget = forms.TextInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(attrs={'class':'form-control'}))






    def clean_firts_name(self):
    	first_name = self.cleaned_data.get('first_name').lower()
    	return first_name
    def clean_last_name(self):
    	last_name = self.cleaned_data.get('last_name').lower()
    	return last_name
    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
      
           raise  ValidationError("Email already exists")
        return email
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1'],
        )
        user.first_name= self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.save()
        return user

1 semestre/TourGuide/apps/Usuario/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate,logout
from apps.Usuario.forms import UserForm,CustomUserCreationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView

from django.core.files.storage import FileSystemStorage
from django.core.files.storage import Storage
from django.core.files.base import ContentFile
from django.contrib.auth.models import User
from apps.Usuario.models import ImagenInfo,HistorialUsuario
from django.urls import reverse_lazy


#Api Google
import io
import os

# Imports the Google Cloud client library
from google.cloud import vision
from google.cloud.vision import types

# Create your views here.




def index(request):
	
	return render(request,'Home/Home.html')

#--------------------------------------------------------
#Solucion opcional al problema del login CSRF verification failed. Request aborted
@login_required
def User_index_view(request):
 
	return render(request,'Usuario/User_Index.html')
#---------------------------------------------------------


#Funcione de autentificacion mediante Email and password
#-----------------------------------------------------------
def user_login(request):
	
	if request.method == 'POST':
		form =  UserForm(request.POST)
		if form.is_valid():
			user = authenticate(
				username = request.POST['email'],
				password = request.POST['password'] 
			)
			if user is not None:
				login(request,user)
				contexto = {'usuarios': user}
				return redirect('login:User_index_view')
			else:
				messages.success(request,"Incorrect user or password")
				
	else:
			form = UserForm()
	return render(request,'Login/Login.html',{'form':form})
#---------------------------------------------------------------------------	

#Funcion de envio y respuesta API Google Vision
@login_required
def info(request):

	os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "melvin-afa24119e798.json"	
	vision_client = vision.ImageAnnotatorClient()
	myfile = request.FILES["file1"]	
	fs = FileSystemStorage()
	filename = fs.save(myfile.name, myfile)
	file_name = fs.url(filename)

	
	with io.open(file_name,"rb") as image_file:
		content = image_file.read()
		image = types.Image(content=content)
	fs.delete(filename)
	response = vision_client.web_detection(image = image)
	#response2 = vision_client.web_detection(image = image)
	annotations = response.web_detection

	label_data =""
	if annotations.web_entities:	
			c = 0
			print('Labels: ')
			for label in annotations.web_entities:
				if(c==0):

					label_data = label_data + label.description
				else:
					break
				c = c+1
	token = ImagenInfo.objects.filter(nombreimagen=label_data).exists()
	if token == True:

		token2 = ImagenInfo.objects.filter(nombreimagen=label_data)
		token3 = User.objects.filter(id= request.user.id)
		
		record =  HistorialUsuario(user = token3[0] ,ImagenInfo=token2[0])
		record.save()

		return render(request,'Usuario/result.html',{"labels":label_data , "image":annotations,"informacion" : token2})
	else:
		
		return render(request,'Usuario/result.html',{"labels":label_data , "image":annotations})

#------------------------------------------------------------------------------------------------------------
#Funcion que consulta y muestra de Historuial del usuario, necesita un User para poder acceder

@login_required
def Historial(request):
	Qhistorial = HistorialUsuario.objects.filter(user = request.user.id )
	contexto = {'objetos' : Qhistorial}
	return render(request,'Usuario/historial.html',contexto)
#Funcion de Ver informacion de la imagen del historial necesita como principal valor el  id de la imagen que se desea observar

@login_required
def view_information(request, imagen_id):
	imagen = ImagenInfo.objects.get(idimagen = imagen_id)
	contexto = {'imagen':imagen}
	return render(request,'Usuario/InfoImagen.html',contexto)

@login_required
def  view_Profile(request,id):
	return render(request,'Usuario/Profile.html')



def register(request):
    if request.method == 'POST':
        f = CustomUserCreationForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'Account created successfully')
            return redirect('login:login')

    else:
        f = CustomUserCreationForm()

    return render(request, 'Usuario/reg_form.html', {'form': f})

'''class RegistroUsuario(CreateView):
	model = User
	template_name = "Usuario/reg_form.html"
	form_class = RegistroForm
	success_url = reverse_lazy('login:login')'''





# Funcion que cierra (elimin la session creada por login(request,user)) a
def logout_view(request):
	logout(request)
	return redirect('index')

1 semestre/TourGuide/templates/Usuario/InfoImagen.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:User_index_view' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>	

				
				<li class="" ><a href="#">{{user.first_name}}</a> </li>	


				<li><a href="#team"> Perfil  </a> </li>
			
<!--				<li>
					<a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal" >Cerrar</a>
				</li>-->

				<li class="nav-item dropdown"><a href="#" >Option</a>
		            <ul >
		              <li><a href="#"><i class="fa fa-folder-open-o"></i>&nbsp Record</a></li>
		              <li><a href="#"><i class="fa fa-address-book"></i> &nbsp Profile</a></li>
		              <li><a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal"> <i class="fa fa-times"></i>  &nbsp Logout</a></li>
		
		            </ul>
		        </li>	
			</ul>
  		</nav>
  	</div>

 </header>
{% endblock %}
{%block content%}
{%endblock%}
{% block portafolio %}

<section id="portfolio">
      <div class="container wow fadeInUp">
        <div class="section-header">
        	<br>
        	<br>
          <h3 class="section-title">Imformation {{imagen.nombreimagen}}</h3>
          <p class="section-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>

		<div class="row" id="">        
          <div class=" portfolio-item filter-app">
          
				{% if imagen %}
				<table class="table table-striped table-advance table-hover ">
					<tbody>
						<tr>
							<th> Tipe &nbsp &nbsp</th>
							<th> Information </th>
						</tr>
						
						<tr>
							<td>Nombre  :</td>
							<td>{{imagen.nombreimagen}}</td>
						</tr>
						<tr>
							<td>Ciudad :</td>
							<td>{{imagen.ciudad}}</td>
						</tr>
						<tr>
							
							<td>Provincia :</td>
							<td>{{imagen.provincia}}</td>
						</tr>
						<tr>
							<td>Distrito :</td>
							<td>{{imagen.distrito}}</td>
						</tr>
						<tr>
							<td>Direccion :</td>
							<td>{{imagen.direccion}}</td>
						</tr>
						<tr>
							<td>Longitud :</td>
							<td>{{imagen.longitud}}</td>
						</tr>
						<tr>
							<td>Latitud :</td>
							<td>{{imagen.latitud}}</td>
						</tr>
						<tr>
							<td>Descripcion :</td>
							<td>{{imagen.description}}</td>
						</tr>
						<tr>
							<td>Construccion :</td>
							<td>{{imagen.construccion}}</td>
						</tr>
						<tr>
							<td>Estilo  :</td>
							<td>{{imagen.estilo_arquitectonico}}</td>
						</tr>
		
					</tbody>

				</table>
				{% endif %}
                   
          </div>

 

        </div>
      </div> 
   </section>
{% endblock %}

1 semestre/TourGuide/templates/Usuario/Profile.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:index' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>
				<li class="" ><a href="">{{user.first_name}}</a> </li>	
				<li class="nav-item dropdown"><a href="" >Drop Down</a>
		            <ul >
		              <li><a href="{% url 'login:Historial' %}"><i class="fa fa-folder-open-o"></i>&nbsp Record</a></li>
		              <li><a href="#"><i class="fa fa-address-book"></i> &nbsp Profile</a></li>
		              <li><a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal"> <i class="fa fa-times"></i>  &nbsp Logout</a></li>
		
		            </ul>
		        </li>

  		</nav>
  	</div>

 </header>
{% endblock %}
{%block content%}


{%endblock%}

{% block services %}

    <!--==========================
      Services Section
    ============================-->
    <section id="contact">
      <div class="container wow fadeInUp">
        <div class="section-header">
          <h3 class="section-title">Profile</h3>

        </div>
      </div>
      <br>	
      <br>	
      <div class="container wow fadeInUp">
        <div class="row justify-content-center">

          <div class="col-lg-3 col-md-4">

            <div class="info">
              <div>
                <i class="fa fa-child"></i>
                <p>{{user.first_name}} <br> {{user.last_name}}</p>
              </div>
              <div>
                <i class="fa fa-envelope"></i>
                <p>{{user.email}}</p>
              </div>
              <div>
                <i class="fa fa-user"></i>
                <p>{{user.username}}</p>
              </div>
               <div>
                <i class="fa fa-calendar"></i>
                <p>{{user.date_joined}}</p>
              </div>
            </div>
          </div>

        </div>

      </div>
    </section><!-- #contact -->








{% endblock %}


{% block portafolio %}


{% endblock %}

1 semestre/TourGuide/templates/Usuario/User_Index.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:index' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>	


				
				<li class="" ><a href="">{{user.first_name}}</a> </li>	



			
		<!--		<li>
					<a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal" >Cerrar</a>
				</li>-->
				<li class="nav-item dropdown"><a href="" >Drop Down</a>
		            <ul >
		              <li><a href="{% url 'login:Historial' %}"><i class="fa fa-folder-open-o"></i>&nbsp Record</a></li>
		              <li><a href="{% url 'login:profile' user.first_name %}"><i class="fa fa-address-book"></i> &nbsp Profile</a></li>
		              <li><a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal"> <i class="fa fa-times"></i>  &nbsp Logout</a></li>
		
		            </ul>
		        </li>

  		</nav>
  	</div>

 </header>
{% endblock %}


{%block content%}


{%endblock%}

{% block services %}

    <!--==========================
      Services Section
    ============================-->

    <section id="services">
      <div class="container wow fadeIn">
      	<br>
      	<br>
      	<div class="section-header">
          	<h3 class="section-title">Image Analyzer</h3>

          	<br>
          	<p class="section-description">Easily detect large sets of objects in your images, from flowers, animals or means of transport to thousands of other categories of objects that often appear in images.</p>
        </div>
		<div class="box">
			
			<h4 class="title"><i class="fa fa-camera"></i>&nbsp Add Image</h4>
		
		
			<div class="drag-drop">
 				 <form action="{% url 'login:rresult' %}" method='post' enctype="multipart/form-data">{% csrf_token %}
        		<input type="file"  id="files" name="file1" />	
        		<br>
        		<br>
       			<output id="list"></output>

		        <script>
		              function archivo(evt) {
		                  var files = evt.target.files; // FileList object
		             
		                  // Obtenemos la imagen del campo "file".
		                  for (var i = 0, f; f = files[i]; i++) {
		                    //Solo admitimos imágenes.
		                    if (!f.type.match('image.*')) {
		                        continue;
		                    }
		             
		                    var reader = new FileReader();
		             
		                    reader.onload = (function(theFile) {
		                        return function(e) {
		                          // Insertamos la imagen
		                         document.getElementById("list").innerHTML = ['<img class="thumb" src="', e.target.result,'" title="', escape(theFile.name), 'WIDTH="400px" HEIGHT="400px" "/>'].join('');
		                        };
		                    })(f);
		             
		                    reader.readAsDataURL(f);
		                  }
		              }
		             
		              document.getElementById('files').addEventListener('change', archivo, false);
		      </script>

			  </div>
			  <br>
			
			 <button type="submit" class="btn btn-outline-secondary">Analyze</button>
			  
			  </form>

		</div>

      </div>
    </section>

{% endblock %}


{% block portafolio %}


{% endblock %}

1 semestre/TourGuide/templates/Usuario/historial.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:User_index_view' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>	

				
				<li class="" ><a href="#">{{user.first_name}}</a> </li>	


				<li><a href="#team"> Perfil  </a> </li>
			
<!--				<li>
					<a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal" >Cerrar</a>
				</li>-->

				<li class="nav-item dropdown"><a href="#" >Option</a>
		            <ul >
		              <li><a href="#"><i class="fa fa-folder-open-o"></i>&nbsp Record</a></li>
		              <li><a href="#"><i class="fa fa-address-book"></i> &nbsp Profile</a></li>
		              <li><a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal"> <i class="fa fa-times"></i>  &nbsp Logout</a></li>
		
		            </ul>
		        </li>	
			</ul>
  		</nav>
  	</div>

 </header>
{% endblock %}
{%block content%}
{%endblock%}
{% block portafolio %}
<section id="portfolio">
      <div class="container wow fadeInUp">
        <div class="section-header">
        	<br>
        	<br>
          <h3 class="section-title">Historial  {{labels}}</h3>
          <p class="section-description"></p>
        </div>
        <table class="table">
			<thead>
				<td>#</td>
				<td>Nombre de lugar turistico</td>
				<td>Fecha</td>
			</thead>
			<tbody>
				{% if objetos %}
				{% for user2 in objetos %}
				<tr>
					<td>{{user2.id}}</td>
					<td>{{user2.ImagenInfo.nombreimagen}}</td>
					<td>{{user2.Register_date}}</td>	

					<td>
						<a class="btn btn-outline-secondary" href="{% url 'login:informacion' user2.ImagenInfo.idimagen %}">Info</a>

					</td>									

				</tr>
				{% endfor%}
				{%endif%}
			</tbody>
		</table>

		
	

      </div> 
    </section>
{% endblock %}

1 semestre/TourGuide/templates/Usuario/reg_form.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:index' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>
                <li>
          <a href="{% url 'login:login' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal" >Login</a>
        </li>
  		</nav>
  	</div>

 </header>
{% endblock %}


{% block lol %}

    <section id="contact">
      <div class="">

        <div class="container wow fadeInUp">
            <div class="section-header">
                <h3 class="section-title">Registro </h3>
                <br>
                <div class="container" >
            <br>
        
            </div>
            </div>
          </div>
        <div class="">
         <div class="">
            <div class="center">
              <div class="col-lg-5 col-md-8">
                  <div class="form">            
                      <div class="form-group">
                        <form  method="POST" > {% csrf_token %} 
                          {{form.as_p}}
                          <center><button type="submit" class="btn btn-primary">Ingresar</button></center>
                      </form>
                      </div>
                     
                  </div>
              </div>
            </div>  
        </div>
      </div>

      </div>

    </section>

{% endblock %}
{%block content%}


{%endblock%}

{% block services %}





{% endblock %}


{% block portafolio %}


{% endblock %}

1 semestre/TourGuide/templates/Usuario/result.html
{% extends 'base/newbase.html' %}


{%block header%}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="{% url 'login:User_index_view' %}"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="" ><a href="{% url 'login:User_index_view' %}"> Home </a> </li>	

				
				<li class="" ><a href="#">{{user.first_name}}</a> </li>	

				<li class="nav-item dropdown"><a href="#" >Option</a>
		            <ul >
		              <li><a href="{% url 'login:Historial' %}"><i class="fa fa-folder-open-o"></i>&nbsp Record</a></li>
		              <li><a href="#"><i class="fa fa-address-book"></i> &nbsp Profile</a></li>
		              <li><a href="{% url 'login:logout' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal"> <i class="fa fa-times"></i>  &nbsp Logout</a></li>
		
		            </ul>
		        </li>	
			</ul>
  		</nav>
  	</div>

 </header>
{% endblock %}
{%block content%}
{%endblock%}
{% block portafolio %}
<section id="portfolio">
      <div class="container wow fadeInUp">
        <div class="section-header">
        	<br>
        	<br>
          <h3 class="section-title">Imformation {{labels}}</h3>
          <p class="section-description">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </div>
        <div class="row">

          <div class="col-lg-12">
            <ul id="portfolio-flters">
              
              <li data-filter=".filter-app"><i class="fa fa-database"></i> &nbsp App</li>
              <li data-filter=".filter-card"><i class="	fa fa-newspaper-o"></i>&nbsp Json</li>
              <li data-filter=".filter-web"><i class="fa fa-paper-plane"></i>&nbspWeb</li>
              <li data-filter=".filter-Map"><i class="fa fa-map-marker"></i>&nbsp Map</li>
            </ul>
          </div>
        </div>	
		
		<div class="row" id="">        
          <div class=" portfolio-item filter-app">
          
				{% if informacion %}
				<table class="table table-striped table-advance table-hover ">
					<tbody>
						<tr>
							<th> Tipe &nbsp &nbsp</th>
							<th> Information </th>
						</tr>
						{% for token2 in informacion %}
						<tr>
							<td>Nombre  :</td>
							<td>{{token2.nombreimagen}}</td>
						</tr>
						<tr>
							<td>Ciudad :</td>
							<td>{{token2.ciudad}}</td>
						</tr>
						<tr>
							
							<td>Provincia :</td>
							<td>{{token2.provincia}}</td>
						</tr>
						<tr>
							<td>Distrito :</td>
							<td>{{token2.distrito}}</td>
						</tr>
						<tr>
							<td>Direccion :</td>
							<td>{{token2.direccion}}</td>
						</tr>
						<tr>
							<td>Longitud :</td>
							<td>{{token2.longitud}}</td>
						</tr>
						<tr>
							<td>Latitud :</td>
							<td>{{token2.latitud}}</td>
						</tr>
						<tr>
							<td>Descripcion :</td>
							<td>{{token2.description}}</td>
						</tr>
						<tr>
							<td>Construccion :</td>
							<td>{{token2.construccion}}</td>
						</tr>
						<tr>
							<td>Estilo  :</td>
							<td>{{token2.estilo_arquitectonico}}</td>
						</tr>
						
				{% endfor %}
		
					</tbody>

				</table>
				{% endif %}
                   
          </div>

          <div class=" portfolio-item filter-web">

				{% if image  %}
				<br>	
				<center>	<h4>Pages with matching images  found:  </h4></center>
				{% endif %}
				<table class="table ">
					<tbody >
						{% for token in image.pages_with_matching_images %}
						<tr >
							<td><a href="{{token.url}}" target="_blank">{{token.url}}</a></td>
						</tr>
						{% endfor %}
					</tbody>
				</table>				
          </div>
         <div class=" portfolio-item filter-card">
				{% if image  %}
				<br>	
				<center><h4>Result Json   :</h4></center>
				{% endif %}
				<table class="table table-striped table-advance table-hover ">
					<tbody>
						<tr>
							<th> Description</th>
							<th>Score</th>
						</tr>

						{% for token in image.web_entities %}
						<tr >
							<td>{{token.description}}</td>
							<td>{{token.score}}</td>
						</tr>

						{% endfor %}
					</tbody>
				</table>
          </div>

         <div style="margin: auto; width: 600%">
         <div class=" portfolio-item filter-Map">

         	<br>
         		<center><h4><i class="fa fa-map-marker"></i> &nbsp Map</h4></center>
				{% for token2 in informacion %}
	         	<div id="googleMap" style="width:100%;height:600px"></div>
				<script>

				var lat= Number.parseFloat("{{token2.longitud}}") ;
		    	var lon= Number.parseFloat("{{token2.latitud}}");
		    	consolo.log(lat);
				function myMap() {

				var mapProp= {
				    center:new google.maps.LatLng(lon,lat),
				    zoom:15,
				};
				var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);
				}
				</script>
				<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCM4omgjzKMYAzu8ZLX0UrA71FLBkMgGLE&callback=myMap"></script>

				{%endfor%}
			
         </div>
 

         </div>



        </div>
      </div> 
    </section>

{% endblock %}