1 semestre/TourGuide/TourGuide/urls.py
from django.contrib import admin
from django.conf.urls import  include
from django.urls import path
from apps.Usuario.views import index


urlpatterns = [
    #path('admin/', admin.site.urls),

    path('',index, name = 'index'),

    path('login/', include('apps.Usuario.urls' , namespace = 'login')),

]

1 semestre/TourGuide/apps/Usuario/urls.py
from django.conf.urls import url, include

from apps.Usuario.views import index,user_login,User_index_view,info,logout_view,Historial,view_information,view_Profile,register
from django.urls import path


app_name = 'apps'
urlpatterns=[

	path('Home/',index, name = "index"),
	path('Login/',user_login,name = "login"),
	path('User/',User_index_view,name='User_index_view'),
	path('Result/',info, name = 'rresult'),
	path('',logout_view, name = 'logout'),
	path('Record/',Historial, name = 'Historial'),
	path('<int:imagen_id>/',view_information, name = 'informacion'),
	path('Profile/<slug:id>/',view_Profile,name='profile'),
	path('reg_form/',register,name='register')


]

1 semestre/TourGuide/templates/base/NewBase.html
{% load staticfiles %}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> {% block title %}TourGuide {% endblock%} </title>

	<link href='/static/img/miniogo.png' rel="icon">
	<link rel="stylesheet" href="{% static 'css/newcss/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/styles1.css'%}">
	<link rel="stylesheet" href="{% static 'css/elegant-icons-style.css'%}">

	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Poppins:300,400,500,700" rel="stylesheet">

	<link rel="stylesheet" href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" >

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


</head>

<body>
<!--==========================
  Header
============================-->
{% block header %}
  <header id = "header">

  	<div class = "container">
  		<div id = "logo" class = "pull-left">
  			<a href="#hero"><img src="/static/img/logos12.png" alt="" title="" /></img></a>
  		</div>
  		<nav id="nav-menu-container">
			<ul class="nav-menu">
				<li class="menu-active" ><a href="#home"> Home </a> </li>	
				<li><a href="#team"> Team </a> </li>
				<li><a href="{% url 'login:register' %}"> Register </a></li>
				<li>
					<a href="{% url 'login:login' %}" data-dismiss="modal" aria-hidden="true" data-toggle="modal" >Login</a>
				</li>
			</ul>
  		</nav>
  	</div>

 </header>
 {% endblock %}


<!--==========================
    Hero Section
============================-->


{% block content %}
	<section id = "hero">
		<div class="hero-container">
			<h1>Welcome to Tour Guide</h1>
			<h2>Analyze your favorite images</h2>
			<a href="#about" class="btn-get-started">Get Started</a>
		</div>	
	</section>	
{% endblock %}


<main id="main">
{%block lol%}


{%endblock%}

{% block services %}
{% endblock %}
{% block portafolio %}
{% endblock %}
</main>


<script src="{% static 'js/jquery/jquery-migrate.min.js' %}"></script>
<script src="{% static 'js/jquery/superfish.min.js' %}"></script>
<script src="{% static 'js/jquery/wow.min.js' %}"></script>
<script src="{% static 'js/jquery/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery/contactform.js' %}"></script>
<script src="{% static 'js/jquery/main.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/jquery.js' %}"></script>






</body>

</html>

1 semestre/TourGuide/templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">


	<title>{% block title %} Document {% endblock %}</title>
</head>
<body>
<div class="container">

{% block navbar %}
    <div class="bs-docs-section clearfix">
        <div class="row">
            <div class="col-lg-12">
                <div class="bs-component">
                 <nav class="navbar navbar-default">
                     <div class="container-fluid">
                        <div class="navbar-header">
                          <a class="navbar-brand" href="#">TourGuide</a>
                        </div>
                       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                         <ul class="nav navbar-nav">
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Mascotas <span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                               <li><a href="{#}">Registrar</a></li>
                               <li><a href="{#}">Listar</a></li>
                              </ul>
                            </li>
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Adopciones<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{#}">Solicitar</a></li>
                                 <li><a href="{#}">Listar solicitudes</a></li>
                              </ul>
                             </li>
                         </ul>
                         <ul class="nav navbar-nav navbar-right">
                             <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
                              <ul class="dropdown-menu" role="menu">
                                 <li><a href="{#}">Salir</a></li>
                              </ul>
                            </li>
                            <li class= "dropdown">
                            	<a href="{% url 'login:login' %}">
                            		Login

                            	</a>

                            </li>
                         </ul>
                        </div>
                    </div>
                </nav>
            </div>
              </div>
          </div>
      </div>

</div>


	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% endblock %}﻿


{% block  content %}



{% endblock %}﻿
	
</body>
</html>